spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  #热部署
  devtools:
    restart:
      enabled: true
      
mybatis:
  # 指定**mapper.xml的位置，默认在使用@mapper标注的Java类同级目录下
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model
  
logging:
  level:
    com.example.demo.mapper: debug